// Code generated by wit-bindgen-go. DO NOT EDIT.

package repro

// This file contains wasmimport and wasmexport declarations for "test:repro".

//go:wasmimport test:repro/repro foo
//go:noescape
func wasmimport_Foo(var0 uint32, var1 uint32)
